version: '3'

services:

  redis-cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - cache:/data

  github-exercise:
    platform: linux/x86_64
    depends_on:
      - redis-cache
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: github-exercise.jar
    ports:
      - "8010:8010"
    networks:
      - default
    environment:
      logging.level.org.springframework: INFO
      server.port: 8010
      spring.profiles.active: local
      redis.url: redis-cache
      redis.port: 6379

volumes:

  cache:
    driver: local
